Repository dennismichol/365_days_planner_app, pull requests merged in 2022-09, with the labels that each got.

#2 Verify Email Dialog stacking
  lib/popup_views/email_verify.dart
  lib/views/onboarding/introduction_page.dart
Labels: bug

#3 Update Gradle version
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  pubspec.lock
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#4 User Session
  lib/main.dart
Labels: bug, help wanted

#9 Refactor Code
  lib/constants/strings.dart
  lib/views/login/login_view.dart
  lib/views/main/components/date_now_card.dart
  lib/views/main/components/divider_with_leadthru.dart
  lib/views/main/components/goals_card.dart
  lib/views/main/components/habits_card.dart
  lib/views/main/components/tasks_card.dart
  lib/views/main/main_view.dart
  lib/views/onboarding/introduction_page.dart
  lib/views/sign_up/components/sign_up_button.dart
  lib/views/sign_up/components/sign_up_fb.dart
  lib/views/sign_up/components/sign_up_google.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#5 Fixed Status Bar Theme
  lib/main.dart
Labels: enhancement
